# NumPy Arrays

### python objects:
     
      1.high-level number objects:integers,floating point
      2.containers: lists (costless insertion and append),dictionaries (fast           lookup)

### numpy provides
    

   1.extention package to Python for multi-dimensional arrays
   2.closer to hardware (efficiency)
   3.designed for scientific computation(convenience)
   4.Also know as array oriented computing

In [5]:
import numpy as np
a = np.array([0,1,2,3])
print(a)

print(np.arange(10))

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


#### why it is useful:Memory-efficient cotainer that provides fast numerical operations

In [9]:
#python lists
L = range(1000)
%timeit [i**2 for i in L]


226 µs ± 6.73 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [10]:
a = np.arange(1000)
%timeit a**2

1.54 µs ± 19.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


### 1.Creating arrays
#### 1.1.Manual construction of arrays


In [6]:
# 1-D
a= np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [7]:
#print dimensions
a.ndim

1

In [8]:
#shape
a.shape

(4,)

In [15]:
b = np.array([[0,1,2],[3,4,5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [16]:
b.ndim


2

In [17]:
b.shape

(2, 3)

In [19]:
len(b) #returns the size of the first dimension 

2

In [9]:
c = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]]])

c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [10]:
c.ndim

3

In [11]:
c.shape

(2, 2, 2)

## 1.2 functions for creating arrays

In [29]:
#using arrange function 

# arange is an array-valued version of the built-in Python range function 

a = np.arange(10) # 0....n-1
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
b = np.arange(1, 10, 2) #start, end (exclusive), step
b

array([1, 3, 5, 7, 9])

In [31]:
#using linspace
a = np.linspace(0,1,6) #start,end,number of points

a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [32]:
#common arrays 

a = np.ones((3,3))

a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [33]:
b = np.zeros((3,3))

b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [47]:
c= np.eye(3)  #Return a 2-D array with ones on the diagonal and zeros elsewhere

c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
d= np.eye(3,2) #3 is number of rows,2 is number of columns, index of diagonal 
d

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [39]:
#create array using diag function

a = np.diag([1,2,3,4])#construct a diagonal array.
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [40]:
np.diag(a)   #Extract diagonal

array([1, 2, 3, 4])

In [48]:
#create array using random 

#create an array of the given shape and populate it with random samples from
a=np.random.rand(4)

a

array([0.60581008, 0.54733228, 0.78078013, 0.01864138])

In [49]:
a = np.random.randn(4)#return a sample (or samples) from the standard normal form
a

array([ 1.84679916, -1.03384638, -0.27783901, -0.45547065])

#### Note:For random samples from N(\sigma^2),use:
sigma*np.random.radn(...)+mu 

# 2.Basic DataTypes

you may have noticed that, in some instances, array elements are displayed with a trailling dot(e.g.2.vs 2.).This is due to a difference in the data-type used:

In [51]:
a = np.arange(10)
a.dtype

dtype('int32')

In [63]:
#you can explicitly specify which data-type you want:

a = np.arange(10, dtype = 'float64')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [64]:
#The default data type is float for zeros and ones function

a=np.zeros((3,3))

print(a)

a.dtype

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

### Other datatypes

In [67]:
d = np.array([1+2j, 2+4j])   #complex datatype

print(d.dtype)

complex128


In [68]:
b = np.array([True,False,True,False])  #boolean datatype

print(b.dtype)

bool


In [69]:
a = np.array(['Ram','Robert','Rahim'])

a.dtype

dtype('<U6')

### Each built-in data type has a character code that uniquely identifies it

'b'-boolean
'i'-(signed)integer
'u'-unsigned integer
'f'-floating-point
'c'-complex-floating point
'm'-timedelta 
'M'-datatime
'O'-(Python) objects
'S','a'-(byte-)string
'U'-unicode
'V'-raw data(void)

For more details
https://docs.scipy.org/doc/numpy-1.10.1/user/basics.types.html


# 3. Indexing and Slicing

## 3.1 indexing

The items of an array can be accessed and assigned to the same way as other Python sequences(e.g.lists):
    

In [80]:
a = np.arange(10)

print(a[5])  #indicates begin at 0, like other Python sequences (and C/c++)

5


In [81]:
#for multidimensional arrays, indexes are tuples of integers:

a = np.diag([1,2,3])

print(a[2,2])


3


In [82]:
a[2,1] = 5 #assigning value 

a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

# 3.2 Slicing

In [83]:
a = np.arange(10)

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
a[1:8:2] #[startindex: endindex(exclusive) :step]

array([1, 3, 5, 7])

In [85]:
#we can also combine assignment and slicing:

a = np.arange(10)
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [86]:
b = np.arange(5)
a[5:] = b[::-1]  #assigning

a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

# 4. copies and views

A slicing operation creates a view on the orginal array, which is just a way of accessing array data.Thus the orginal array is not copied in memory. You can use np.may_share_memory0 to check if two arrays share the same memory block.

#### when modifying the view, the orginal array is modified as well:



In [87]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
b=a[::2]
b

array([0, 2, 4, 6, 8])

In [89]:
np.shares_memory(a,b)

True

In [90]:
b[0] = 10
b

array([10,  2,  4,  6,  8])

In [93]:
a  #eventhough we modified b, it updated 'a' because both shares same memory

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [15]:
a = np.arange(10)

c = a[::2].copy()    #force a copy
c

array([0, 2, 4, 6, 8])

In [16]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
np.shares_memory(a,c)

False

In [96]:
c[0] = 10

a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 5.Fancy indexing

NumPy arrays can be indexed with slices, but also with boolean or integer arrays(masks).This method is called is called fancy indexing. it creates copies not views.

### Using Boolean Mask

In [98]:
a = np.random.randint(0,20,15)
a

array([ 7,  3,  3,  7, 11,  6, 10,  2,  4,  7,  3, 17,  6, 15,  7])

In [100]:
mask = (a % 2 == 0)

In [101]:
extract_from_a =a[mask]

extract_from_a

array([ 6, 10,  2,  4,  6])

#### Indexing with a mask can be very useful to assign a new value to a sub-array:

In [102]:
a[mask] = -1
a

array([ 7,  3,  3,  7, 11, -1, -1, -1, -1,  7,  3, 17, -1, 15,  7])

#### Indexing with an array of integers 

In [103]:
a = np.arange(0,100,10)

a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [104]:
#indexing can be done with an array of integers, where the same index is repeated
a[[2,3,2,4,2]]

array([20, 30, 20, 40, 20])

In [105]:
# New  values can be assigned

a[[9, 7]] = -200

a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])